# Mouse
set -g mouse off

# Mouse toggle
bind m set -g mouse \; display-message "Mouse: #{?mouse,ON,OFF}"

# Copy mode
set -g mode-keys vi

# Status bar
set -g status on
set -g status-position bottom

# Status format
set -g status-format[0] '#[align=left]#[bold]  Dashboard     #[default]#[align=centre]#[bold]Mouse: #{?mouse,ON,OFF} (Ctrl+B → m)#[align=right]#{?client_prefix,#[bold] PREFIX MODE #[default],} #S '

# Click Dashboard
bind -n MouseDown1StatusLeft run-shell 'tmuxp load -y ~/.config/tmuxp/dashboard.yaml'